version: '3'
services:
  mongodb:
    image:  my-mongodb
    container_name: mongodb-container
    ports:
      - "27017:27017"
  express-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: express-app-container
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    env_file:
      - .env